# Generated by Django 5.2.4 on 2025-08-06 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('bio', models.TextField(blank=True, verbose_name='السيرة الذاتية')),
                ('link', models.URLField(blank=True, verbose_name='الرابط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مؤلف',
                'verbose_name_plural': 'المؤلفون',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدورة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('instructor', models.CharField(blank=True, max_length=100, verbose_name='المعلم')),
                ('link', models.URLField(blank=True, verbose_name='الرابط')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='المدة')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='المستوى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دورة تعليمية',
                'verbose_name_plural': 'الدورات التعليمية',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='اسم المستخدم')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('link', models.URLField(blank=True, verbose_name='الرابط')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='النوع')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('language', models.CharField(default='العربية', max_length=50, verbose_name='اللغة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_agent.author', verbose_name='المؤلف')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'الكتب',
            },
        ),
    ]
