# Generated by Django 5.2.4 on 2025-08-12 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم العربي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم العربي')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('website', models.URLField(blank=True, verbose_name='الموقع')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
            },
        ),
        migrations.CreateModel(
            name='EnhancedAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم العربي')),
                ('bio', models.TextField(blank=True, verbose_name='السيرة الذاتية')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='المهنة')),
                ('profile_pic', models.ImageField(blank=True, upload_to='library_authors/')),
                ('wikipedia', models.URLField(blank=True, verbose_name='ويكيبيديا')),
                ('youtube', models.URLField(blank=True, verbose_name='يوتيوب')),
                ('twitter', models.URLField(blank=True, verbose_name='تويتر')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_url', models.URLField(blank=True, verbose_name='الرابط المختصر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مؤلف',
                'verbose_name_plural': 'المؤلفون',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('title_ar', models.CharField(max_length=300, verbose_name='العنوان العربي')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('summary', models.TextField(blank=True, verbose_name='الملخص')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='AI_agent.category', verbose_name='الفئات')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_agent.enhancedauthor', verbose_name='المؤلف')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
            },
        ),
        migrations.CreateModel(
            name='EnhancedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('title_ar', models.CharField(max_length=300, verbose_name='العنوان العربي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='النوع')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('language', models.CharField(default='العربية', max_length=50, verbose_name='اللغة')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_agent.enhancedauthor', verbose_name='المؤلف')),
                ('categories', models.ManyToManyField(blank=True, to='AI_agent.category', verbose_name='الفئات')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'الكتب',
            },
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم العربي')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('url', models.URLField(verbose_name='الرابط')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='AI_agent.category', verbose_name='الفئات')),
            ],
            options={
                'verbose_name': 'تطبيق ويب',
                'verbose_name_plural': 'تطبيقات الويب',
            },
        ),
    ]
